create sequence hibernate_sequence start 1 increment 1;
CREATE TABLE weather_data (
    temperature_celsius DOUBLE PRECISION,
    temperature_fahrenheit DOUBLE PRECISION,
    condition_text VARCHAR(255),
    wind_kph DOUBLE PRECISION,
    wind_degree INT,
    wind_direction VARCHAR(255),
    pressure_mb DOUBLE PRECISION,
    pressure_in DOUBLE PRECISION,
    precip_mm DOUBLE PRECISION,
    precip_in DOUBLE PRECISION,
    humidity INT,
    cloud INT,
    feels_like_celsius DOUBLE PRECISION,
    feels_like_fahrenheit DOUBLE PRECISION,
    visibility_km DOUBLE PRECISION,
    visibility_miles DOUBLE PRECISION,
    uv_index INT,
    air_quality_Carbon_Monoxide DOUBLE PRECISION,
    air_quality_Ozone DOUBLE PRECISION,
    air_quality_Nitrogen_dioxide DOUBLE PRECISION,
    air_quality_Sulphur_dioxide DOUBLE PRECISION,
    air_quality_PM10 DOUBLE PRECISION
);
INSERT INTO weather_data(
    temperature_celsius,
    temperature_fahrenheit,
    condition_text,
    wind_kph,
    wind_degree,
    wind_direction,
    pressure_mb,
    pressure_in,
    precip_mm,
    precip_in,
    humidity,
    cloud,
    feels_like_celsius,
    feels_like_fahrenheit,
    visibility_km,
    visibility_miles,
    uv_index,
    air_quality_Carbon_Monoxide,
    air_quality_Ozone,
    air_quality_Nitrogen_dioxide,
    air_quality_Sulphur_dioxide,
    air_quality_PM10
)
SELECT
    temperature_celsius,
    temperature_fahrenheit,
    condition_text,
    wind_kph,
    wind_degree,
    wind_direction,
    pressure_mb,
    pressure_in,
    precip_mm,
    precip_in,
    humidity,
    cloud,
    feels_like_celsius,
    feels_like_fahrenheit,
    visibility_km,
    visibility_miles,
    uv_index,
    air_quality_Carbon_Monoxide,
    air_quality_Ozone,
    air_quality_Nitrogen_dioxide,
    air_quality_Sulphur_dioxide,
    air_quality_PM10
FROM weather;